# Generated by Django 6.0.2 on 2026-05-04 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Malzeme Adı')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarif Adı')),
                ('prep_time', models.CharField(max_length=50, verbose_name='Hazırlanma Süresi')),
                ('difficulty', models.CharField(max_length=50, verbose_name='Zorluk Derecesi')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('instructions', models.TextField(blank=True, help_text='Adımları sırasıyla alt alta yazın.', null=True, verbose_name='Hazırlanışı')),
                ('servings', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kaç Kişilik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Kapak Fotoğrafı')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Resim URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_text', models.CharField(blank=True, help_text='Örn: 2 diş, 500 gram, 1 yemek kaşığı', max_length=100, null=True, verbose_name='Miktar/Birim')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Tarif Malzemesi',
                'verbose_name_plural': 'Tarif Malzemeleri',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='Malzemeler'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', '-created_at'], name='recipes_rec_author__0ddfe9_idx'),
        ),
    ]
