# Generated by Django 6.0.2 on 2026-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Kolay', 'Kolay'), ('Orta', 'Orta'), ('Zor', 'Zor')], max_length=10, verbose_name='Zorluk Derecesi'),
        ),
    ]
