# Generated by Django 6.0.2 on 2026-05-08 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_difficulty_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('rating', models.IntegerField(blank=True, help_text='1 ile 5 arası puan', null=True, verbose_name='Puan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Tarif Yorumu',
                'verbose_name_plural': 'Tarif Yorumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
