# Generated by Django 6.0.2 on 2026-05-05 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Malzeme Adı')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Kısa Açıklama')),
                ('hazirlanma_suresi', models.CharField(max_length=50, verbose_name='Hazırlanma Süresi')),
                ('zorluk', models.CharField(choices=[('Kolay', 'Kolay'), ('Orta', 'Orta'), ('Zor', 'Zor')], max_length=10, verbose_name='Zorluk')),
                ('porsiyon', models.CharField(blank=True, max_length=50, verbose_name='Porsiyon')),
                ('talimatlar', models.TextField(blank=True, verbose_name='Talimatlar')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='tarifler/', verbose_name='Resim')),
                ('resim_url', models.URLField(blank=True, null=True, verbose_name='Resim URL')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('guncelleme', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifler', to='tarifler.kategori', verbose_name='Kategori')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifler_yonetim', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='TarifMalzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.CharField(blank=True, max_length=100, verbose_name='Miktar/Birim')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_malzemeleri', to='tarifler.malzeme')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_malzemeleri', to='tarifler.tarif')),
            ],
            options={
                'verbose_name': 'Tarif Malzemesi',
                'verbose_name_plural': 'Tarif Malzemeleri',
            },
        ),
        migrations.AddIndex(
            model_name='tarif',
            index=models.Index(fields=['yazar', '-olusturulma'], name='tarifler_ta_yazar_i_d696c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tarif',
            index=models.Index(fields=['kategori'], name='tarifler_ta_kategor_75cc12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifmalzeme',
            unique_together={('tarif', 'malzeme')},
        ),
    ]
