from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from apps.recipes.models import Recipe, Ingredient, RecipeIngredient


RECIPES = [
    {'title': 'Fırın Sütlaç', 'prep_time': '50 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'Fırında kızarmış klasik Türk sütlacı. Kremsi dokusu ve enfes aromasıyla sofraların vazgeçilmezi.', 'instructions': 'Pirinçleri yıkayıp 30 dakika suda bekletin.\nSüt ile pirinçleri orta ateşte, sürekli karıştırarak pişirin.\nPirinçler yumuşayınca şeker ve vanilyayı ekleyin.\nKoyulaşan karışımı fırın kaplarına dökün.\nÖnceden ısıtılmış 200°C fırında üzeri kızarana kadar pişirin.', 'image_url': 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Pirinç', '1 su bardağı'), ('Süt', '1 litre'), ('Şeker', '1 su bardağı'), ('Vanilya', '1 paket'), ('Nişasta', '2 yemek kaşığı')]},
    {'title': 'Mercimek Çorbası', 'prep_time': '35 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Sıcacık ve doyurucu kırmızı mercimek çorbası. Limon ve kırmızı biberle servis edilir.', 'instructions': 'Soğan ve havucu yağda kavurun.\nYıkanan mercimekleri ve sıcak suyu ekleyin.\nTuz, kimyon ve zerdeçalı ilave edip 25 dakika pişirin.\nBlender ile pürüzsüz hale getirin.\nTereyağında kırmızı biber ve nane kavurarak üzerine dökün.', 'image_url': 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Kırmızı Mercimek', '2 su bardağı'), ('Soğan', '1 adet'), ('Havuç', '1 adet'), ('Tereyağı', '2 yemek kaşığı'), ('Kimyon', '1 tatlı kaşığı'), ('Kırmızı Biber', '1 tatlı kaşığı')]},
    {'title': 'Karnıyarık', 'prep_time': '60 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Kıymalı iç harcıyla doldurulmuş, fırında pişirilmiş geleneksel patlıcan yemeği.', 'instructions': 'Patlıcanları soyup tuzlu suda 20 dakika bekletin.\nYağda kızartıp kağıt havlu üzerinde yağını alın.\nSoğan ve kıymayı kavurun, domates ve biber ekleyin.\nPatlıcanları ortadan yarıp iç harcı doldurun.\nÜzerine domates dilimleri koyup 180°C fırında 30 dakika pişirin.', 'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Patlıcan', '4 adet'), ('Kıyma', '300 gram'), ('Soğan', '2 adet'), ('Domates', '3 adet'), ('Yeşil Biber', '2 adet'), ('Sarımsak', '3 diş'), ('Sıvıyağ', '1/2 su bardağı')]},
    {'title': 'Çikolatalı Sufle', 'prep_time': '25 dk', 'difficulty': 'Zor', 'servings': '4 Kişilik', 'description': 'Dışı çıtır içi sıvı akan fondant sufle. Sıcak servis edildiğinde mükemmel bir lezzet.', 'instructions': 'Çikolata ve tereyağını benmari usulü eritin.\nYumurta ve şekeri çırpın, eriyen çikolatayı ekleyin.\nUnu eleyin ve hafifçe karıştırın.\nYağlanmış kaplara dökün ve buzdolabında 30 dakika bekletin.\n200°C fırında tam 12 dakika pişirip hemen servis yapın.', 'image_url': 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Bitter Çikolata', '150 gram'), ('Tereyağı', '100 gram'), ('Yumurta', '3 adet'), ('Şeker', '80 gram'), ('Un', '2 yemek kaşığı')]},
    {'title': 'İmam Bayıldı', 'prep_time': '55 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Soğan ve sarımsaklı zeytinyağlı dolma patlıcan. Soğuk servis edildiğinde daha lezzetlidir.', 'instructions': 'Patlıcanları tuzlu suda bekletip süzün.\nZeytinyağında soğan ve sarımsağı kavurun.\nDomates, maydanoz ve baharatları ekleyin.\nPatlıcanları yağda hafifçe kavurun.\nHarcı doldurun ve düşük ateşte 30 dakika pişirin.', 'image_url': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Patlıcan', '3 adet'), ('Soğan', '3 adet'), ('Sarımsak', '5 diş'), ('Domates', '4 adet'), ('Zeytinyağı', '1/2 su bardağı'), ('Maydanoz', '1 demet')]},
    {'title': 'Tavuk Şiş', 'prep_time': '40 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Marine edilmiş tavuk parçalarından hazırlanan ızgara şiş. Sebzelerle birlikte servis edilir.', 'instructions': 'Tavukları küp küp kesin.\nYoğurt, zeytinyağı, sarımsak ve baharatlarla marine edin.\nEn az 2 saat buzdolabında bekletin.\nŞişlere geçirip ızgarada veya mangalda pişirin.\nYanında lavaş, soğan ve mevsim salatasıyla servis edin.', 'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Tavuk Göğsü', '600 gram'), ('Yoğurt', '3 yemek kaşığı'), ('Zeytinyağı', '2 yemek kaşığı'), ('Sarımsak', '3 diş'), ('Kırmızı Biber', '1 tatlı kaşığı'), ('Kimyon', '1 tatlı kaşığı')]},
    {'title': 'Lahmacun', 'prep_time': '50 dk', 'difficulty': 'Orta', 'servings': '6 Kişilik', 'description': 'İnce hamur üzerine baharatlı kıyma harcıyla hazırlanan Türk pizzası. Limon ve maydanozla servis edilir.', 'instructions': 'Un, tuz, su ve mayayı yoğurup 30 dakika dinlendirin.\nKıyma, soğan, domates, biber ve baharatları karıştırın.\nHamuru ince açın, üzerine harcı yayın.\n250°C fırında 8-10 dakika pişirin.\nÜzerine limon sıkıp maydanoz ve soğanla servis edin.', 'image_url': 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Un', '3 su bardağı'), ('Kıyma', '400 gram'), ('Soğan', '2 adet'), ('Domates', '2 adet'), ('Kırmızı Biber Salçası', '1 yemek kaşığı'), ('Maydanoz', '1 demet'), ('İnce Kırmızı Biber', '1 tatlı kaşığı')]},
    {'title': 'Baklava', 'prep_time': '90 dk', 'difficulty': 'Zor', 'servings': '12 Kişilik', 'description': 'Tereyağlı yufkalar arasında antep fıstığı ile hazırlanan şerbetli Türk tatlısı.', 'instructions': 'Şerbeti hazırlayıp soğumaya bırakın.\nYufkaları eritilmiş tereyağıyla yağlayarak tepsiye dizin.\nOrtasına öğütülmüş fıstık yayın, kalan yufkaları üstüne dizin.\nDilimleyip 180°C fırında altın rengi alana kadar pişirin.\nFırından çıkınca soğuk şerbeti sıcak baklavaya dökün.', 'image_url': 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Yufka', '500 gram'), ('Antep Fıstığı', '300 gram'), ('Tereyağı', '250 gram'), ('Şeker', '2 su bardağı'), ('Su', '2 su bardağı'), ('Limon Suyu', '1 yemek kaşığı')]},
    {'title': 'Menemen', 'prep_time': '20 dk', 'difficulty': 'Kolay', 'servings': '2 Kişilik', 'description': 'Domates, biber ve yumurtadan oluşan klasik Türk kahvaltısı. Sucuklu veya sade yapılabilir.', 'instructions': 'Zeytinyağında doğranmış soğanı kavurun.\nBiber ve domatesleri ekleyip suyunu çekene kadar pişirin.\nTuz ve karabiber ekleyin.\nYumurtaları kırıp karıştırın.\nYumurtalar pişince ocaktan alın, sıcak servis edin.', 'image_url': 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Yumurta', '3 adet'), ('Domates', '2 adet'), ('Yeşil Biber', '2 adet'), ('Soğan', '1 adet'), ('Zeytinyağı', '2 yemek kaşığı'), ('Tuz', 'Tatmak için')]},
    {'title': 'Künefe', 'prep_time': '30 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Kadayıf ve tuzlu peynirden yapılan, şerbetli geleneksel Türk tatlısı.', 'instructions': 'Şerbeti hazırlayıp soğumaya bırakın.\nKadayıfı eritilmiş tereyağıyla yoğurun.\nYarısını tepsiye basın, üzerine rendelenmiş peynir yayın.\nKalan kadayıfı üstüne koyup bastırın.\nOrta ateşte her iki tarafı altın rengi alana kadar pişirin, şerbet dökün.', 'image_url': 'https://images.unsplash.com/photo-1571167530149-c1105da4d61a?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Tel Kadayıf', '400 gram'), ('Tuzlu Peynir', '300 gram'), ('Tereyağı', '150 gram'), ('Şeker', '1.5 su bardağı'), ('Su', '1.5 su bardağı'), ('Antep Fıstığı', '50 gram')]},
    {'title': 'Zeytinyağlı Taze Fasulye', 'prep_time': '45 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Hafif ve sağlıklı, yaz sofralarının vazgeçilmez zeytinyağlı klasiği.', 'instructions': '1. Fasulyeleri yıkayıp uçlarını kesin ve ikiye bölün.\n2. Soğanları yemeklik, domatesleri küp küp doğrayın.\n3. Tencereye sırasıyla soğan, fasulye ve domatesleri kat kat dizin.\n4. Zeytinyağı, tuz ve şekeri üzerinde gezdirin.\n5. Tencerenin kapağını kapatıp kendi suyuyla kısık ateşte yaklaşık 40 dakika pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=100', 'ingredients': [('Taze Fasulye', '500 gram'), ('Büyük Kuru Soğan', '1 adet'), ('Domates', '3 adet'), ('Zeytinyağı', '1 çay bardağı'), ('Toz Şeker', '1 tatlı kaşığı'), ('Tuz', '1 tatlı kaşığı')]},
    {'title': 'Kuru Fasulye & Pilav', 'prep_time': '90 dk', 'difficulty': 'Orta', 'servings': '6 Kişilik', 'description': 'Geleneksel Türk mutfağının ayrılmaz ikilisi, tam bir protein deposu ev yemeği.', 'instructions': '1. Geceden ıslatılmış fasulyeleri bol suda hafif diri kalacak şekilde haşlayın.\n2. Ayrı bir tencerede soğanı sıvı yağ ile kavurun.\n3. Salçayı ekleyip kokusu çıkana kadar kavurmaya devam edin.\n4. Haşlanıp süzülmüş fasulyeleri ekleyerek 1-2 tur karıştırın.\n5. Üzerini 3-4 parmak geçecek kadar sıcak su, toz biber ve tuzu ilave edin.\n6. Kısık ateşte helmelenene kadar (yaklaşık 45-60 dk) pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=101', 'ingredients': [('Kuru Fasulye Geceden Islatılmış', '2 su bardağı'), ('Soğan', '1 adet'), ('Biber Salçası', '1.5 yemek kaşığı'), ('Sıvı Yağ', '3 yemek kaşığı'), ('Kırmızı Toz Biber', '1 tatlı kaşığı'), ('Tuz', '')]},
    {'title': 'Tavuklu Sebzeli Erişte', 'prep_time': '25 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Evinizdeki mevsim sebzeleriyle rahatça zenginleştirebileceğiniz, hızlı ve doyurucu bir öğün.', 'instructions': '1. Erişteleri tuzlu kaynar suda 8-10 dakika haşlayın.\n2. Tavukları jülyen (gelişigüzel ince uzun) doğrayıp geniş bir tavada az yağ ile soteleyin.\n3. İnce uzun doğranmış biberleri ekleyip tavuklarla beraber kavurun.\n4. Haşlanan erişteyi süzüp tavaya ilave edin.\n5. Soya sosunu ekleyin, tüm malzemeleri 2-3 dakika harmanlayın ve sıcak servis yapın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=102', 'ingredients': [('Köy Eriştesi', '1 paket'), ('Tavuk Göğsü', '250g'), ('Kapya Biber', '1 adet'), ('Yeşil Biber', '2 adet'), ('Soya Sosu', '2 yemek kaşığı'), ('Sıvı Yağ', ''), ('Tuz', '')]},
    {'title': 'Zerdeçallı Pirinç Pilavı', 'prep_time': '30 dk', 'difficulty': 'Kolay', 'servings': '4-6 Kişilik', 'description': 'Hem rengiyle göze, hem aromasıyla damağa hitap eden, farklılık arayanlara şık pilav.', 'instructions': '1. Pirinçleri 15 dakika ılık ve tuzlu suda bekletip nişastasından arınana kadar iyice yıkayın.\n2. Tencerede tereyağını eritin. Suyu süzülen pirinçleri ekleyip 3-4 dakika şeffaflaşana kadar kavurun.\n3. Zerdeçalı ekleyip rengi tamamen pirinçlere geçene kadar 1 dakika daha kavurun.\n4. Sıcak suyu ve tuzu ekleyin.\n5. Kısık ateşte suyunu tamamen çekene kadar pişirin. Demlendikten sonra tane tane servis edin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=103', 'ingredients': [('Baldo Pirinç', '2 su bardağı'), ('Tereyağı', '3 yemek kaşığı'), ('Toz Zerdeçal', '1 tatlı kaşığı'), ('Tavuk Suyu', '3 su bardağı'), ('Tuz', '')]},
    {'title': 'Pratik Bezelye Yemeği', 'prep_time': '35 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Havuç ve patatesle zenginleşen, ev malzemeleriyle şipşak hazırlanan sulu yemek.', 'instructions': '1. Soğanı yemeklik doğrayın, havuç ve patatesleri küp küp kesin.\n2. Zeytinyağında soğanı pembeleşene dek kavurun.\n3. Havuçları ekleyip birkaç dakika da havuçlarla kavurun.\n4. Salçayı ilave edip 1 dakika daha kavurun.\n5. Bezelye ve patatesleri ekleyin. Üzerini geçecek kadar sıcak su ve tuzu ilave edip sebzeler yumuşayana (yaklaşık 25-30 dk) kadar pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=104', 'ingredients': [('Bezelye', '500 gram'), ('Patates', '1 adet'), ('Büyük Havuç', '1 adet'), ('Kuru Soğan', '1 adet'), ('Domates Salçası', '1.5 yemek kaşığı'), ('Zeytinyağı', ''), ('Tuz', '')]},
    {'title': 'Şakşuka', 'prep_time': '40 dk', 'difficulty': 'Orta', 'servings': '6 Kişilik', 'description': 'Küçük doğranıp kızarmış sebzelerin nefis domates sosuyla buluştuğu meze veya garnitür.', 'instructions': '1. Tüm sebzeleri aynı boyutta, küçük küpler halinde doğrayın.\r\n2. Sıvı yağda sırasıyla patates, patlıcan, kabak ve sivri biberi kızartıp fazla yağını peçeteye süzün.\r\n3. Sos için sarımsakları zeytinyağında hafifçe çevirin, rendelenmiş domatesleri ve sirkeyi ekleyin.\r\n4. Sos suyunu hafif çekip kıvam aldığında kızarmış sebzeleri sosa ilave edip çok karıştırmadan harmanlayın. Soğuk ya da ılık servis edin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=105', 'ingredients': [('Patlıcan', '3 adet'), ('Kabak', '2 adet'), ('Sivri Biber', '3 adet'), ('Büyük Patates', '1 adet'), ('Domates', '4 adet'), ('Sarımsak', '3 diş'), ('Sirke', '1 tatlı kaşığı'), ('Tuz', '')]},
    {'title': 'Ev Yapımı Çıtır Patates', 'prep_time': '45 dk', 'difficulty': 'Kolay', 'servings': '3-4 Kişilik', 'description': 'Fırında az yağ ile hazırlanan, dışı çıtır içi yumuşacık sağlıklı atıştırmalık.', 'instructions': '1. Patatesleri soyun, elma dilimi veya parmak şeklinde doğrayın.\n2. Doğranmış patatesleri soğuk suda 10 dakika bekletip nişastasını saldıktan sonra kağıt havluyla tamamen kurulayın.\n3. Geniş bir kapta zeytinyağı, mısır unu, baharatlar ve tuzu karıştırın.\n4. Kurulanmış patatesleri bu harca bulayın.\n5. Yağlı kağıt serilmiş tepsiye üst üste gelmeyecek şekilde dizin.\n6. Önceden ısıtılmış 200 derece fırında kızarana kadar (yaklaşık 35-40 dk) pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=106', 'ingredients': [('Kızartmalık Patates', '4 adet'), ('Zeytinyağı', '3 yemek kaşığı'), ('Mısır Unu Veya Nişasta', '1 tatlı kaşığı'), ('Kırmızı Toz Biber', '1 çay kaşığı'), ('Kekik', '1 çay kaşığı'), ('Tuz', ''), ('Sarımsak Tozu', '')]},
    {'title': 'Humuslu Tavuk Köftesi', 'prep_time': '40 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Yüksek proteinli, nohut ezmesi ve tavuğun bir araya geldiği yenilikçi fit tarif.', 'instructions': '1. Derin bir yoğurma kabına tavuk kıymasını alın.\n2. Üzerine humus, çok ince kıyılmış soğan, yumurta, galeta unu ve baharatları ekleyin.\n3. Tüm malzemeler bütünleşene kadar yaklaşık 5 dakika yoğurun. Harç cıvık kalırsa biraz daha galeta unu ekleyebilirsiniz.\n4. Karışımı buzdolabında 20 dakika dinlendirin.\n5. Elinizi hafifçe ıslatarak harçtan ceviz büyüklüğünde parçalar koparıp yassı köfte şekli verin.\n6. Az yağlanmış yanmaz tavada veya fırında iki tarafı da altın rengi olana kadar pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=107', 'ingredients': [('Tavuk Kıyması', '500 gram'), ('Humus Veya Nohut', '3 yemek kaşığı'), ('Yumurta', '1 adet'), ('Küçük Kuru Soğan', '1'), ('Galeta Unu', '2 yemek kaşığı'), ('Kimyon', '1 çay kaşığı'), ('Tuz', ''), ('Karabiber', '')]},
    {'title': 'İskender Kebap', 'prep_time': '45 dk', 'difficulty': 'Zor', 'servings': '2 Kişilik', 'description': "Bursa'nın meşhur döner kebabı.", 'instructions': '1. Etleri ince ince dilimleyip pişirin.\n2. Pideleri doğrayıp tereyağında soteleyin.\n3. Pidelerin üzerine etleri, salçalı sosu ve tereyağını gezdirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=108', 'ingredients': [('Dana Eti', '400 gram'), ('Pide', '2 adet'), ('Tereyağı', '3 yemek kaşığı'), ('Domates Salçası', '2 yemek kaşığı'), ('Yoğurt', '1 kase')]},
    {'title': 'Süzme Mercimek Çorbası', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'İçinizi ısıtacak klasik ve lezzetli bir çorba.', 'instructions': '1. Mercimek ve sebzeleri yıkayıp tencereye alın.\n2. Su ekleyip sebzeler yumuşayana kadar kaynatın.\n3. Blenderdan geçirip tereyağlı sos ile servis yapın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=109', 'ingredients': [('Kırmızı Mercimek', '1 su bardağı'), ('Soğan', '1 adet'), ('Havuç', '1 adet'), ('Patates', '1 adet'), ('Tereyağı', '1 yemek kaşığı')]},
    {'title': 'Ev Yapımı Mantı', 'prep_time': '60 dk', 'difficulty': 'Zor', 'servings': '4 Kişilik', 'description': 'Kayseri usulü, sarımsaklı yoğurt ve salçalı sosla servis edilen el yapımı mantı.', 'instructions': '1. Hamuru yoğurup dinlendirin ve ince açın.\n2. Kıymalı harcı kare hamurların içine koyup kapatın.\n3. Suda haşlayıp üzerine yoğurt ve sos dökün.', 'image_url': 'https://loremflickr.com/800/600/food?lock=110', 'ingredients': [('Un', '3 su bardağı'), ('Yumurta', '1 adet'), ('Kıyma', '200 gram'), ('Soğan', '1 adet'), ('Yoğurt', '2 kase')]},
    {'title': 'Zeytinyağlı Yaprak Sarma', 'prep_time': '45 dk', 'difficulty': 'Zor', 'servings': '6 Kişilik', 'description': 'İncecik sarılmış, bol limonlu zeytinyağlı sarma.', 'instructions': '1. İç harcı kavurun ve soğumaya bırakın.\n2. Asma yapraklarını açıp iç harçtan koyarak ince ince sarın.\n3. Tencereye dizip zeytinyağı ve su ekleyerek pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=111', 'ingredients': [('Asma Yaprağı', '500 gram'), ('Pirinç', '2 su bardağı'), ('Soğan', '3 adet'), ('Zeytinyağı', '1 çay bardağı'), ('Limon', '1 adet')]},
    {'title': 'Adana Kebap', 'prep_time': '30 dk', 'difficulty': 'Zor', 'servings': '4 Kişilik', 'description': 'Acılı ve baharatlı gerçek Adana kebap.', 'instructions': '1. Zırhla çekilmiş kıymaya kırmızı toz biber ve kuyruk yağı ekleyip yoğurun.\n2. Şişlere geçirip mangalda veya ızgarada pişirin.\n3. Lavaş ve soğan salatası ile servis yapın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=112', 'ingredients': [('Kuzu Kıyma', '500 gram'), ('Kuyruk Yağı', '100 gram'), ('Toz Kırmızı Biber', '1 yemek kaşığı'), ('Tuz', '1 tatlı kaşığı')]},
    {'title': 'Urfa Kebap', 'prep_time': '30 dk', 'difficulty': 'Zor', 'servings': '4 Kişilik', 'description': 'Acısız, sade ve lezzetli Urfa kebabı.', 'instructions': '1. Kıymayı sadece tuz ile yoğurun.\n2. Şişlere sıkıca sararak geçirin.\n3. Izgarada çevirerek pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=113', 'ingredients': [('Dana Kıyma', '400 gram'), ('Kuzu Kıyma', '200 gram'), ('Tuz', '1 tatlı kaşığı')]},
    {'title': 'İçli Köfte', 'prep_time': '60 dk', 'difficulty': 'Zor', 'servings': '8 Kişilik', 'description': 'Dışı ince bulgur, içi cevizli kıymalı eşsiz lezzet.', 'instructions': '1. İç harcı hazırlayıp soğutun.\n2. Bulgurlu hamuru yoğurun ve şekil vererek içini oyun.\n3. Harcı doldurup kapatın ve kızartın veya haşlayın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=114', 'ingredients': [('İnce Bulgur', '2 su bardağı'), ('Kıyma', '300 gram'), ('Ceviz', '1 çay bardağı'), ('Soğan', '2 adet'), ('Salça', '1 yemek kaşığı')]},
    {'title': 'Etli Çiğ Köfte', 'prep_time': '60 dk', 'difficulty': 'Zor', 'servings': '6 Kişilik', 'description': 'Geleneksel yoğurmalı etli çiğ köfte.', 'instructions': '1. Bulgur ve baharatları salça ile yoğurmaya başlayın.\n2. Yağsız ince çekilmiş eti ekleyip uzun süre yoğurun.\n3. Yeşillik ve buz ilave ederek kıvam alana kadar yoğurup sıkım yapın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=115', 'ingredients': [('Esmer İnce Bulgur', '3 su bardağı'), ('Yağsız Kıyma', '250 gram'), ('İsot', '3 yemek kaşığı'), ('Domates Salçası', '2 yemek kaşığı')]},
    {'title': 'Hünkar Beğendi', 'prep_time': '30 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Köz patlıcanlı yatağında yumuşacık et sote.', 'instructions': '1. Etleri kuşbaşı doğrayıp yumuşayana kadar pişirin.\n2. Patlıcanları közleyip soyun ve ezerek kaşarlı beğendi hazırlayın.\n3. Beğendinin üzerine etleri ekleyerek servis yapın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=116', 'ingredients': [('Kuşbaşı Et', '400 gram'), ('Patlıcan', '4 adet'), ('Kaşar Peyniri', '1 çay bardağı'), ('Süt', '1 su bardağı')]},
    {'title': 'Tas Kebabı', 'prep_time': '20 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Lokanta usulü, patatesli enfes tas kebabı.', 'instructions': '1. Etleri kendi suyunu salıp çekene kadar kavurun.\n2. Soğan, salça ve patatesleri ekleyip su ilave edin.\n3. Kısık ateşte etler lokum gibi olana kadar pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=117', 'ingredients': [('Dana Kuşbaşı', '500 gram'), ('Patates', '2 adet'), ('Soğan', '1 adet'), ('Domates Salçası', '1 yemek kaşığı')]},
    {'title': 'Ali Nazik Kebap', 'prep_time': '25 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Köz patlıcan ve yoğurtlu taban üzerine kıyma kavurması.', 'instructions': '1. Patlıcanları közleyip yoğurt ve sarımsakla karıştırın.\n2. Kıymayı tereyağı ve baharatlarla kavurun.\n3. Patlıcanlı harcın üzerine kıymayı döküp servis edin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=118', 'ingredients': [('Kıyma', '300 gram'), ('Patlıcan', '3 adet'), ('Süzme Yoğurt', '1 kase'), ('Sarımsak', '2 diş')]},
    {'title': 'Patlıcan Musakka', 'prep_time': '30 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Kızarmış patlıcan halkaları ve lezzetli kıymalı harç.', 'instructions': '1. Patlıcanları halka doğrayıp kızartın.\n2. Kıymalı iç harcı tavada hazırlayın.\n3. Tencereye bir kat patlıcan, bir kat harç dizip salçalı su ekleyerek pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=119', 'ingredients': [('Patlıcan', '4 adet'), ('Kıyma', '250 gram'), ('Soğan', '1 adet'), ('Biber', '2 adet')]},
    {'title': 'Etli Kuru Fasulye', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'Milli yemeğimiz, bol salçalı etli kuru fasulye.', 'instructions': '1. Fasulyeleri bir gece önceden ıslatın.\n2. Eti kavurup üzerine soğan ve salça ekleyin.\n3. Fasulyeleri ilave edip düdüklüde pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=120', 'ingredients': [('Kuru Fasulye', '2 su bardağı'), ('Kuşbaşı Et', '200 gram'), ('Soğan', '1 adet'), ('Domates Salçası', '2 yemek kaşığı')]},
    {'title': 'Etli Nohut Yemeği', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'Suyuna ekmek banmalık klasik ev yemeği.', 'instructions': '1. Nohutları haşlayın.\n2. Tencerede eti, soğanı ve salçayı kavurun.\n3. Nohutları ve sıcak suyu ekleyip özleşene kadar pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=121', 'ingredients': [('Nohut', '2 su bardağı'), ('Kuşbaşı Et', '200 gram'), ('Soğan', '1 adet'), ('Salça', '2 yemek kaşığı')]},
    {'title': 'Tereyağlı Şehriyeli Pilav', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Tane tane dökülen tereyağlı pirinç pilavı.', 'instructions': '1. Pirinçleri sıcak suda nişastası gidene kadar yıkayın.\n2. Şehriyeleri tereyağında kavurup pirinçleri ekleyin.\n3. Sıcak su ve tuz ilave edip kısık ateşte demlenerek pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=122', 'ingredients': [('Baldo Pirinç', '2 su bardağı'), ('Arpa Şehriye', 'Yarım çay bardağı'), ('Tereyağı', '2 yemek kaşığı'), ('Sıcak Su', '3 su bardağı')]},
    {'title': 'Sebzeli Bulgur Pilavı', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Domates ve biberle tatlandırılmış doyurucu bulgur pilavı.', 'instructions': '1. Soğan, biber ve domatesi sıvı yağda kavurun.\n2. Salça ve bulguru ekleyip biraz daha kavurun.\n3. Sıcak su ekleyip suyunu çekene kadar pişirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=123', 'ingredients': [('Pilavlık Bulgur', '2 su bardağı'), ('Domates', '2 adet'), ('Yeşil Biber', '2 adet'), ('Soğan', '1 adet')]},
    {'title': 'Hatay Usulü Kısır', 'prep_time': '30 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'Bol nar ekşili ve salçalı ince bulgur salatası.', 'instructions': '1. Bulguru sıcak su ile ıslatıp şişmesini bekleyin.\n2. Salça, baharatlar ve zeytinyağı ile iyice yoğurun.\n3. İnce doğranmış yeşillikleri ve nar ekşisini ekleyip karıştırın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=124', 'ingredients': [('İnce Bulgur', '2 su bardağı'), ('Biber Salçası', '2 yemek kaşığı'), ('Taze Soğan', '5 dal'), ('Maydanoz', '1 demet'), ('Nar Ekşisi', 'Yarım çay bardağı')]},
    {'title': 'Mercimek Köftesi', 'prep_time': '30 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'Çay saatlerinin vazgeçilmezi klasik lezzet.', 'instructions': '1. Mercimekleri haşlayıp içine ince bulguru katın ve dinlendirin.\n2. Soğan ve salçayı kavurup bulgurlu karışıma ekleyin.\n3. Yeşillikleri katıp yoğurun ve elinizle şekil verin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=125', 'ingredients': [('Kırmızı Mercimek', '1 su bardağı'), ('İnce Bulgur', '1.5 su bardağı'), ('Soğan', '1 adet'), ('Maydanoz', 'Yarım demet')]},
    {'title': 'Ezogelin Çorbası', 'prep_time': '10 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'Nane ve pul biberle lezzetlendirilmiş yöresel çorba.', 'instructions': '1. Mercimek, bulgur ve pirinci yıkayıp tencereye alın.\n2. Su ekleyip yumuşayana kadar kaynatın.\n3. Ayrı bir tavada salçalı ve naneli sos hazırlayıp çorbaya ilave edin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=126', 'ingredients': [('Kırmızı Mercimek', '1 su bardağı'), ('Pirinç', '1 yemek kaşığı'), ('Bulgur', '1 yemek kaşığı'), ('Nane', '1 tatlı kaşığı')]},
    {'title': 'Yayla Çorbası', 'prep_time': '10 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Yoğurtlu, naneli hafif çorba.', 'instructions': '1. Pirinci suda yumuşayana kadar haşlayın.\n2. Yoğurt, un ve yumurta sarısını çırpıp terbiye yapın.\n3. Çorbanın suyundan terbiyeye ekleyip ılıtın, sonra hepsini birleştirin. Üzerine naneli yağ gezdirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=127', 'ingredients': [('Yoğurt', '1.5 su bardağı'), ('Pirinç', 'Yarım çay bardağı'), ('Yumurta', '1 adet'), ('Un', '1 yemek kaşığı'), ('Nane', '1 tatlı kaşığı')]},
    {'title': 'Kremalı Domates Çorbası', 'prep_time': '10 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Kaşar peyniri rendesiyle servis edilen klasik domates çorbası.', 'instructions': '1. Unu tereyağında kokusu çıkana kadar kavurun.\n2. Salça ve domates rendesini ekleyip pişirin.\n3. Su ve sütü ilave edip kaynayana kadar karıştırın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=128', 'ingredients': [('Domates', '4 adet'), ('Tereyağı', '1 yemek kaşığı'), ('Un', '2 yemek kaşığı'), ('Süt', 'Yarım su bardağı')]},
    {'title': 'Tarhana Çorbası', 'prep_time': '5 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Kış aylarının şifası ev yapımı tarhana.', 'instructions': '1. Tarhanayı 1 bardak soğuk suyla ezin.\n2. Tencerede salça ve naneyi kavurun.\n3. Tarhanayı ve sıcak suyu ekleyip kaynayana kadar sürekli karıştırın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=129', 'ingredients': [('Toz Tarhana', '4 yemek kaşığı'), ('Domates Salçası', '1 tatlı kaşığı'), ('Nane', '1 tatlı kaşığı'), ('Tereyağı', '1 yemek kaşığı')]},
    {'title': 'Kazandibi', 'prep_time': '20 dk', 'difficulty': 'Orta', 'servings': '4 Kişilik', 'description': 'Yanık şekerin eşsiz aromasıyla sütlü tatlı.', 'instructions': '1. Süt, şeker, un ve nişastayı karıştırarak muhallebi pişirin.\n2. Tepsinin tabanına pudra şekeri serpip ocakta karamelize edin.\n3. Muhallebiyi üzerine döküp soğuttuktan sonra rulo yaparak servis edin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=130', 'ingredients': [('Süt', '1 litre'), ('Toz Şeker', '1 su bardağı'), ('Pirinç Unu', '3 yemek kaşığı'), ('Nişasta', '2 yemek kaşığı')]},
    {'title': 'Yalancı Tavuk Göğsü', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'İçinde tavuk olmadan hazırlanan, sakız kıvamında hafif tatlı.', 'instructions': '1. Tereyağında unu hafif kavurun.\n2. Süt ve şekeri ekleyip sürekli karıştırarak koyulaşana kadar pişirin.\n3. Vanilya ekleyip mikserle 10 dakika çırpın ve borcama dökün.', 'image_url': 'https://loremflickr.com/800/600/food?lock=131', 'ingredients': [('Süt', '1 litre'), ('Tereyağı', '125 gram'), ('Un', '1 su bardağı'), ('Toz Şeker', '1.5 su bardağı'), ('Vanilya', '1 paket')]},
    {'title': 'Şekerpare', 'prep_time': '20 dk', 'difficulty': 'Orta', 'servings': '8 Kişilik', 'description': 'Ağızda dağılan, şerbetli enfes şekerpare.', 'instructions': '1. Şerbeti kaynatıp soğumaya bırakın.\n2. Margarin, pudra şekeri, yumurta ve irmikle hamuru yoğurup şekil verin.\n3. Fırında kızarana kadar pişirin ve fırından çıkar çıkmaz soğuk şerbeti dökün.', 'image_url': 'https://loremflickr.com/800/600/food?lock=132', 'ingredients': [('Tereyağı', '125 gram'), ('İrmik', 'Yarım su bardağı'), ('Pudra Şekeri', 'Yarım su bardağı'), ('Un', '2 su bardağı'), ('Şeker', '3 su bardağı')]},
    {'title': 'Revani', 'prep_time': '15 dk', 'difficulty': 'Orta', 'servings': '8 Kişilik', 'description': 'İrmikli sünger keki ve tam kıvamında şerbetiyle.', 'instructions': '1. Yumurta ve şekeri çırpıp yoğurt, yağ, irmik ve unu ekleyin.\n2. Fırında kızarana kadar pişirin.\n3. Ilık kekin üzerine soğuk şerbeti gezdirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=133', 'ingredients': [('İrmik', '1 su bardağı'), ('Un', '1 su bardağı'), ('Yoğurt', '1 su bardağı'), ('Yumurta', '3 adet'), ('Şeker', '3 su bardağı')]},
    {'title': 'Erzurum Kadayıf Dolması', 'prep_time': '30 dk', 'difficulty': 'Zor', 'servings': '6 Kişilik', 'description': 'Cevizle sarılmış tel kadayıfın yumurtaya bulanıp kızartılması.', 'instructions': '1. Tel kadayıfın içine ceviz koyup sarma gibi sarın.\n2. Çırpılmış yumurtaya bulayıp bol yağda kızartın.\n3. Kızaran dolmaları hemen soğuk şerbete atıp çıkarın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=134', 'ingredients': [('Tel Kadayıf', '300 gram'), ('Ceviz', '1 su bardağı'), ('Yumurta', '3 adet'), ('Şeker', '2 su bardağı')]},
    {'title': 'Ramazan Güllacı', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '6 Kişilik', 'description': 'Sütlü ve cevizli hafif iftar tatlısı.', 'instructions': '1. Sütü şekerle ısıtıp ılıtın.\n2. Güllaç yapraklarını tepsiye dizerken aralarına ılık süt gezdirin.\n3. Orta kata ceviz serpip kalan yaprakları da aynı şekilde ıslatın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=135', 'ingredients': [('Güllaç Yaprağı', '10 yaprak'), ('Süt', '1.5 litre'), ('Şeker', '1.5 su bardağı'), ('Ceviz', '1 su bardağı')]},
    {'title': 'Bolluk Bereket Aşuresi', 'prep_time': '120 dk', 'difficulty': 'Zor', 'servings': '10 Kişilik', 'description': 'Nohut, fasulye, buğday ve kuru meyvelerin muhteşem uyumu.', 'instructions': '1. Bakliyatları bir gece önceden ıslatıp haşlayın.\n2. Buğdayı iyice haşlayıp diğer malzemeleri, şeker ve kuru meyveleri ekleyerek kaynatın.\n3. Kıvam alınca kaselere paylaştırıp nar ve tarçınla süsleyin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=136', 'ingredients': [('Aşurelik Buğday', '2 su bardağı'), ('Nohut', '1 su bardağı'), ('Kuru Fasulye', '1 su bardağı'), ('Kuru İncir', '1 çay bardağı'), ('Şeker', '3 su bardağı')]},
    {'title': 'İrmik Helvası', 'prep_time': '10 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Dondurma eşliğinde servis edebileceğiniz nefis irmik helvası.', 'instructions': '1. Tereyağında çam fıstığı ve irmiği rengi dönene kadar kavurun.\n2. Ayrı bir yerde su, süt ve şekeri kaynatıp şerbet yapın.\n3. Sıcak şerbeti kavrulmuş irmiğe döküp demlendirin.', 'image_url': 'https://loremflickr.com/800/600/food?lock=137', 'ingredients': [('İrmik', '1.5 su bardağı'), ('Tereyağı', '3 yemek kaşığı'), ('Şeker', '1.5 su bardağı'), ('Süt', '1 su bardağı'), ('Su', '1 su bardağı')]},
    {'title': 'Un Helvası', 'prep_time': '5 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Az malzemeli, tam ölçülü un helvası.', 'instructions': '1. Tereyağı ve sıvı yağı tavada ısıtıp unu ekleyin ve rengi kahverengi olana kadar kavurun.\n2. Şerbetini (su ve şeker) soğuk olarak hazırlayın.\n3. Kavrulan una şerbeti ekleyip hızla karıştırarak toparlanmasını sağlayın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=138', 'ingredients': [('Un', '2 su bardağı'), ('Tereyağı', '100 gram'), ('Sıvı Yağ', 'Yarım çay bardağı'), ('Şeker', '1.5 su bardağı'), ('Su', '1.5 su bardağı')]},
    {'title': 'Kemalpaşa Tatlısı', 'prep_time': '5 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Hazır alınan kemalpaşa peynir tatlısının şerbetlenmesi.', 'instructions': '1. Suyu ve şekeri tencereye alıp kaynatın.\n2. Tatlıları şerbete atıp yumuşayana kadar pişirin.\n3. Üzerine tahin ve ceviz dökerek servis yapın.', 'image_url': 'https://loremflickr.com/800/600/food?lock=139', 'ingredients': [('Kemalpaşa Tatlısı', '1 paket'), ('Şeker', '2 su bardağı'), ('Su', '2.5 su bardağı'), ('Tahin', 'İsteğe bağlı')]},
    {'title': 'Tavuk Suyuna Tel Şehriyeli Çorba', 'prep_time': '15 dk', 'difficulty': 'Kolay', 'servings': '4 Kişilik', 'description': 'Hastalık zamanlarında içimi rahatlatan, tam şifa niyetine klasik ev çorbası.', 'instructions': '1. Tavuğu haşlayıp suyunu ayırın ve etlerini didikleyin.\n2. Tencerede sıvı yağ ile şehriyeleri hafifçe kavurun.\n3. Üzerine sıcak tavuk suyunu ekleyip kaynamaya bırakın.\n4. Şehriyeler yumuşayınca didiklenmiş tavuk etlerini ekleyin.\n5. Tuz, karabiber ve limon suyu ilave edip 5 dakika daha kaynattıktan sonra sıcak servis yapın.', 'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80', 'ingredients': [('Tavuk Göğsü', '1 adet'), ('Tel Şehriye', 'Yarım çay bardağı'), ('Tavuk Suyu', '5 su bardağı'), ('Sıvı Yağ', '2 yemek kaşığı'), ('Limon', 'Yarım adet'), ('Tuz', '1 çay kaşığı')]},
]


class Command(BaseCommand):
    help = '51 örnek tarif ekler'

    def handle(self, *args, **options):
        user = User.objects.filter(is_superuser=True).first()
        if not user:
            user = User.objects.first()
        if not user:
            self.stderr.write('Önce bir kullanıcı oluşturun: python3 manage.py createsuperuser')
            return

        created = 0
        for data in RECIPES:
            if Recipe.objects.filter(title=data['title']).exists():
                self.stdout.write(f'  zaten var: {data["title"]}')
                continue

            recipe = Recipe.objects.create(
                title=data['title'],
                prep_time=data['prep_time'],
                difficulty=data['difficulty'],
                servings=data['servings'],
                description=data['description'],
                instructions=data['instructions'],
                image_url=data['image_url'],
                author=user,
            )

            for ing_name, qty in data['ingredients']:
                ingredient, _ = Ingredient.objects.get_or_create(name=ing_name)
                RecipeIngredient.objects.create(
                    recipe=recipe,
                    ingredient=ingredient,
                    quantity_text=qty,
                )

            created += 1
            self.stdout.write(self.style.SUCCESS(f'  ✓ {recipe.title}'))

        total_count = Recipe.objects.count()
        self.stdout.write(self.style.SUCCESS(f'\n{created} tarif eklendi.'))
        self.stdout.write(self.style.SUCCESS(f'Toplam tarif sayısı: {total_count}'))
        print("RECIPES LENGTH:", len(RECIPES))
