# Generated by Django 6.0.2 on 2026-03-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarif Adı')),
                ('prep_time', models.CharField(max_length=50, verbose_name='Hazırlanma Süresi')),
                ('difficulty', models.CharField(max_length=50, verbose_name='Zorluk Derecesi')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Resim URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='avatars/', verbose_name='Profil Fotoğrafı')),
                ('newsletter', models.BooleanField(default=True, verbose_name='Bülten Bildirimleri')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.recipe')),
            ],
        ),
    ]
