# Generated by Django 6.0.2 on 2026-03-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Her bir malzemeyi yeni bir satıra yazın.', null=True, verbose_name='Malzemeler'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Adımları sırasıyla alt alta yazın.', null=True, verbose_name='Hazırlanışı'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kaç Kişilik'),
        ),
    ]
