# Generated by Django 6.0.2 on 2026-04-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe_ingredients_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Malzeme Adı')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Sadece eski verileri tutmak için.', null=True, verbose_name='Eski Malzemeler (Metin)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='core.ingredient', verbose_name='Malzemeler'),
        ),
    ]
