# Generated by Django 6.0.2 on 2026-04-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_list',
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_text', models.CharField(blank=True, help_text='Örn: 2 diş, 500 gram, 1 yemek kaşığı', max_length=100, null=True, verbose_name='Miktar/Birim')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='core.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='core.recipe')),
            ],
            options={
                'verbose_name': 'Tarif Malzemesi',
                'verbose_name_plural': 'Tarif Malzemeleri',
            },
        ),
    ]
