# Generated by Django 6.0.2 on 2026-04-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_recipe_ingredient_list_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='core.RecipeIngredient', to='core.ingredient', verbose_name='Malzemeler'),
        ),
    ]
